### PR TITLE
fix admin settings save process

### PR DESCRIPTION
**Pull request by timelf123**
process was reversed credits to old PR here https://github.com/linnovate/mean/pull/1511/commits/25c5a71206de67bea9ea187e7f72af91c94317cb

### CODE REVIEW

**Comment by jwebbdev** [comment]
@timelf123 Can you rebase this and we'll put it in?  Going to push new versions of the core stuff to npm and update linnovate/mean package.jsons to get npm and not repos.

**Review by timelf123 — COMMENTED** [review]
oops, hasty merge

**Comment by jwebbdev** [comment]
Is that comment referring to the merge stuff in the PR?  HEAD>>> etc?  If not... Check it out :)

**Comment by timelf123** [comment]
Yes, I'll get back in there today and clean it up ;)

**Comment by timelf123** [comment]
Good for review

**Pull request merged**
